# Shouldn't need to be changed if you are using Windows.
environment:
  python: venv/Scripts/python.exe
  webui: webui.py

# Default config

default: # You can add additional key : value parameters here
  ckpt: model.ckpt
  port: # if you change this, it needs to be in quotes "7860"
  ui-config: ui-config.json
  ui-settings: config.json
  extra-params: #you can add additional parameters here that don't require a value
    -  # --medvram
    -  # --opt-split-attention

# Add your own
